name: Release

on:
  push:
    branches:
      - develop

jobs:
  release:
    uses: jondotsoy/jondotsoy/.github/workflows/bun-release-package.yml@v1
    secrets:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
