name: Release

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Lint
        run: bun lint

  release:
    needs: lint
    uses: jondotsoy/jondotsoy/.github/workflows/bun-release-package.yml@v1
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
