name: Release

on:
  push:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v3
        with:
            key: key
            path: ~/.bun/install/cache
      - run: bun install
      - name: Lint
        run: |
          bun lint 2&> /tmp/lint_report || touch /tmp/lint_report_fail
          if [[ -f /tmp/lint_report_fail ]]; then
            cat /tmp/lint_report
            echo "## Error Lint" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            cat /tmp/lint_report >> $GITHUB_STEP_SUMMARY
            echo "```" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

  release:
    needs: lint
    uses: jondotsoy/jondotsoy/.github/workflows/bun-release-package.yml@v1
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
