name: Release Github Page

on:
  push:
    branches:
      - demo-page

jobs:
  release-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v3
        with:
          key: bun-install-cache-${{ runner.arch }}-${{ runner.os }}-${{ github.workflow }}
          path: ~/.bun/install/cache
      - run: bun install
      - run: bun astro build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
